### ISSUE TITLE
Issue with GraheneOS ?

### ISSUE THREAD

**Issue by NablaMetal** [0x50f13/NextcloudServices#78]
Hello,
I don't know why but with my Pixel 7 on GrapheneOS (latest build 2024040900 - Android 14), the last working release of NextcloudServices was 1.0-beta17.
1.0-beta18 crashes instantaneously.
1.0-beta19 just don't display notifications.

Except the reply for talk/spreed notifications, 1.0-beta17 do work (login through the Nextcloud app).
Is it possible I misconfigured something ?

**Comment by thiswillbeyourgithub** [comment]
Hi, also on grapheneos here. Discovered this app recently so I only rester 1.0-beta19 and indeed I never received any notification.

**Comment by 0x50f13** [comment]
Hello, sorry for long response. I would try installing GrapheneOS on my currently unused Pixel 8 and testing app there. Though it would be great if you would be able to provide some logs, if possible

**Comment by thiswillbeyourgithub** [comment]
Thanks!

I don't see anything relevant but there you go:
[Nextcloud Services log 9bcdedc4a03b.txt](https://github.com/0x50f13/NextcloudServices/files/15138660/Nextcloud.Services.log.9bcdedc4a03b.txt)

**Comment by freeflyk** [comment]
Hi 0x50f13. I'm on LineageOS 21 (Android 14) and have the same problem. I had a look into it and found that the problem lies within the mutable pending intents, for which handling has changed in Android 14 (https://developer.android.com/about/versions/14/behavior-changes-14?hl=en#safer-intents). I implemented a fix which works for my LOS21 and created a pull request.

**Comment by 0x50f13** [comment]
Closed in PR #79

**Comment by NablaMetal** [comment]
@thiswillbeyourgithub @0x50f13 @freeflyk thanks a lot !

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot for the fix!

Is there an apk available with this fix? I don't have a compiling setup ready

**Comment by freeflyk** [comment]
@thiswillbeyourgithub : you can download the automatically generated apk from the actions section oft this repo. You have to be logged in to see the download button...

**Comment by thiswillbeyourgithub** [comment]
Dear god after years and years on github I shomehow never knew that, thank you so sososo much!
The fix works great btw
